### ISSUE TITLE
Suggestion: .Net Standard SDK

### ISSUE THREAD

**Issue by rhaley-starfish** [qualisys/RTClientSDK.Net#6]
Hi, 

I am working to create a .Net Standard implementation and had to create my own project and import the classes. Perhaps you could/should convert the SDK to .Net Standard project so it will work with .Net Framework and .Net Core? It will also make the change over to .Net 5 easier when it gets released... 

Just a suggestion. :)

**Comment by mlveggo** [comment]
Yes.

We will make it work easier with .net core. Publishing on nuget for easier use is also something we aim for.

Thanks for the suggestion.
